[build]
  publish = "web"
  command = "echo 'Skipping build step - static deployment only'"
  
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    
[dev]
  framework = "#static"

# Explicitly disable Python
[build.environment]
  NETLIFY_USE_PYTHON = "false" 